services:
  # Full-stack application (Backend + Frontend)
  - type: web
    name: tracksite-python5
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: USE_POSTGRESQL
        value: "true"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:xxxxxxxxxxxx@ep-round-mode-a5m8qkz9.us-east-2.aws.neon.tech/neondb?sslmode=require"